version: "3.9"

services:
  dialab:
    build: .
    container_name: dialab
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
